# Generated by Django 4.2.27 on 2026-01-23 10:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_component_svg'),
    ]

    operations = [
        migrations.CreateModel(
            name='CanvasState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=100)),
                ('x', models.FloatField()),
                ('y', models.FloatField()),
                ('width', models.FloatField()),
                ('height', models.FloatField()),
                ('rotation', models.FloatField(default=0)),
                ('scaleX', models.FloatField(default=1)),
                ('scaleY', models.FloatField(default=1)),
                ('sequence', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Connection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sourceGripIndex', models.IntegerField()),
                ('targetGripIndex', models.IntegerField()),
                ('waypoints', models.JSONField()),
                ('sourceItemId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sources', to='api.canvasstate')),
                ('targetItemId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='targets', to='api.canvasstate')),
            ],
        ),
        migrations.AddField(
            model_name='project',
            name='description',
            field=models.CharField(blank=True, default=None, max_length=2000, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='component',
            name='grips',
            field=models.JSONField(default=list),
        ),
        migrations.AlterField(
            model_name='component',
            name='s_no',
            field=models.CharField(max_length=10, unique=True),
        ),
        migrations.DeleteModel(
            name='ProjectComponent',
        ),
        migrations.AddField(
            model_name='canvasstate',
            name='component',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.component'),
        ),
        migrations.AddField(
            model_name='canvasstate',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.project'),
        ),
    ]
