# Generated by Django 4.2.27 on 2026-01-13 15:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0005_canvasstate_connection_project_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='component',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='component',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='canvasstate',
            name='component',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='api.component'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='component',
            name='png',
            field=models.ImageField(blank=True, null=True, upload_to='components/'),
        ),
        migrations.AlterField(
            model_name='component',
            name='svg',
            field=models.FileField(blank=True, null=True, upload_to='components/'),
        ),
    ]
