# Generated by Django 4.2.27 on 2026-01-13 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_component_created_at_component_created_by_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='component',
            name='legend',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='component',
            name='suffix',
            field=models.CharField(blank=True, max_length=10),
        ),
    ]
