export const componentData = [
  {
    s_no: "101",
    parent: "General",
    name: "Insulation/Tracing",
    legend: "",
    suffix: "",
    object: "Insulation",
    svg: "",
    png: "",
    grips: "",
  },
  {
    s_no: "201",
    parent: "Process Quantities",
    name: "Liquid Flow",
    legend: "",
    suffix: "",
    object: "LiquidFlow",
    svg: "",
    png: "",
    grips: "",
  },
  {
    s_no: "202",
    parent: "Process Quantities",
    name: "Gas Flow",
    legend: "",
    suffix: "",
    object: "GasFlow",
    svg: "",
    png: "",
    grips: "",
  },
  {
    s_no: "203",
    parent: "Process Quantities",
    name: "Pressure and Temperature",
    legend: "",
    suffix: "",
    object: "PressureAndTemperature",
    svg: "",
    png: "",
    grips: "",
  },
  {
    s_no: "301",
    parent: "Piping",
    name: "Inflow Line",
    legend: "",
    suffix: "",
    object: "InflowLine",
    svg: "",
    png: "",
    grips: "",
  },
  {
    s_no: "302",
    parent: "Piping",
    name: "Outflow Line",
    legend: "",
    suffix: "",
    object: "OutflowLine",
    svg: "",
    png: "",
    grips: "",
  },
  {
    s_no: "303",
    parent: "Piping",
    name: "Connecting Line",
    legend: "",
    suffix: "",
    object: "ConnectingLine",
    svg: "",
    png: "",
    grips: "",
  },
  {
    s_no: "304",
    parent: "Piping",
    name: "Cross Over Line",
    legend: "",
    suffix: "",
    object: "CrossOverLine",
    svg: "",
    png: "",
    grips: "",
  },
  {
    s_no: "305",
    parent: "Piping",
    name: "Direction of Process Flow",
    legend: "",
    suffix: "",
    object: "DirectionProcessFlow",
    svg: "",
    png: "",
    grips: "",
  },
  {
    s_no: "306",
    parent: "Piping",
    name: "Slope of a Process Line",
    legend: "",
    suffix: "",
    object: "SlopeProcessLine",
    svg: "",
    png: "",
    grips: "",
  },
  {
    s_no: "307",
    parent: "Piping",
    name: "Dead End",
    legend: "",
    suffix: "",
    object: "DeadEnd",
    svg: "",
    png: "",
    grips: "",
  },
  {
    s_no: "308",
    parent: "Piping",
    name: "Buried Line",
    legend: "",
    suffix: "",
    object: "BuriedLine",
    svg: "",
    png: "",
    grips: "",
  },
  {
    s_no: "309",
    parent: "Piping",
    name: "Vendor Limit Line",
    legend: "",
    suffix: "",
    object: "VendorLimitLine",
    svg: "",
    png: "",
    grips: "",
  },
  {
    s_no: "310",
    parent: "Piping",
    name: "Tracing",
    legend: "",
    suffix: "",
    object: "Tracing",
    svg: "",
    png: "",
    grips: "",
  },
  {
    s_no: "311",
    parent: "Piping",
    name: "Change of Pipe Specification",
    legend: "",
    suffix: "",
    object: "ChangePipeSpecification",
    svg: "",
    png: "",
    grips: "",
  },
  {
    s_no: "312",
    parent: "Piping",
    name: "Centre Line",
    legend: "",
    suffix: "",
    object: "CenterLine",
    svg: "",
    png: "",
    grips: "",
  },
  {
    s_no: "313",
    parent: "Piping",
    name: "Coil",
    legend: "",
    suffix: "",
    object: "Coil",
    svg: "",
    png: "",
    grips: "",
  },
  {
    s_no: "314",
    parent: "Piping",
    name: "Process Line",
    legend: "",
    suffix: "",
    object: "ProcessLine",
    svg: "",
    png: "",
    grips: "",
  },
  {
    s_no: "315",
    parent: "Piping",
    name: "Jacketted Line",
    legend: "",
    suffix: "",
    object: "JackettedLine",
    svg: "",
    png: "",
    grips: "",
  },
  {
    s_no: "401",
    parent: "Valves",
    name: "Gate Valve",
    legend: "PRV",
    suffix: "A/B",
    object: "GateValve",
    svg: "",
    png: "",
    grips: "",
  },
  {
    s_no: "402",
    parent: "Valves",
    name: "Globe Valve",
    legend: "PRV",
    suffix: "A/B",
    object: "GlobeValve",
    svg: "",
    png: "",
    grips: "",
  },
  {
    s_no: "403",
    parent: "Valves",
    name: "Check Valve",
    legend: "PRV",
    suffix: "A/B",
    object: "CheckValve",
    svg: "",
    png: "",
    grips: "",
  },
  {
    s_no: "404",
    parent: "Valves",
    name: "Angle Valve",
    legend: "PRV",
    suffix: "A/B",
    object: "AngleValve",
    svg: "",
    png: "",
    grips: "",
  },
  {
    s_no: "405",
    parent: "Valves",
    name: "Diaphragm Valve",
    legend: "PRV",
    suffix: "A/B",
    object: "DiaphragmValve",
    svg: "",
    png: "",
    grips: "",
  },
  {
    s_no: "406",
    parent: "Valves",
    name: "Safety Valve",
    legend: "PRV",
    suffix: "A/B",
    object: "SafetyValve",
    svg: "",
    png: "",
    grips: "",
  },
  {
    s_no: "407",
    parent: "Valves",
    name: "Ball Valve",
    legend: "PRV",
    suffix: "A/B",
    object: "BallValve",
    svg: "",
    png: "",
    grips: "",
  },
  {
    s_no: "408",
    parent: "Valves",
    name: "Solenoid Valve",
    legend: "PRV",
    suffix: "A/B",
    object: "SolenoidValve",
    svg: "",
    png: "",
    grips: "",
  },
  {
    s_no: "409",
    parent: "Valves",
    name: "Float Valve",
    legend: "PRV",
    suffix: "A/B",
    object: "FloatValve",
    svg: "",
    png: "",
    grips: "",
  },
  {
    s_no: "410",
    parent: "Valves",
    name: "Butterfly Valve",
    legend: "PRV",
    suffix: "A/B",
    object: "ButterflyValve",
    svg: "",
    png: "",
    grips: "",
  },
  {
    s_no: "411",
    parent: "Valves",
    name: "Regulating Globe Valve",
    legend: "PRV",
    suffix: "A/B",
    object: "RegulatingGlobeValve",
    svg: "",
    png: "",
    grips: "",
  },
  {
    s_no: "412",
    parent: "Valves",
    name: "Foot Valve With Strainer",
    legend: "PRV",
    suffix: "A/B",
    object: "FootValveStrainer",
    svg: "",
    png: "",
    grips: "",
  },
  {
    s_no: "413",
    parent: "Valves",
    name: "Plug Valve",
    legend: "PRV",
    suffix: "A/B",
    object: "PlugValve",
    svg: "",
    png: "",
    grips: "",
  },
  {
    s_no: "414",
    parent: "Valves",
    name: "Control Valve",
    legend: "PRV",
    suffix: "A/B",
    object: "ControlValve",
    svg: "",
    png: "",
    grips: "",
  },
  {
    s_no: "415",
    parent: "Valves",
    name: "Piston Operated Hydraulic Control Valve",
    legend: "PRV",
    suffix: "A/B",
    object: "PistonOperatedHydraulicControlValve",
    svg: "",
    png: "",
    grips: "",
  },
  {
    s_no: "416",
    parent: "Valves",
    name: "Electrically Operated Control Valve",
    legend: "PRV",
    suffix: "A/B",
    object: "ElecticallyOperatedControlValve",
    svg: "",
    png: "",
    grips: "",
  },
  {
    s_no: "417",
    parent: "Valves",
    name: "Pinch Valve",
    legend: "PRV",
    suffix: "A/B",
    object: "PinchValve",
    svg: "",
    png: "",
    grips: "",
  },
  {
    s_no: "418",
    parent: "Valves",
    name: "Spring Loaded Valve",
    legend: "PRV",
    suffix: "A/B",
    object: "SpringLoadedValve",
    svg: "",
    png: "",
    grips: "",
  },
  {
    s_no: "419",
    parent: "Valves",
    name: "Control Valve with Hand Wheel",
    legend: "PRV",
    suffix: "A/B",
    object: "ControlValveHandWheel",
    svg: "",
    png: "",
    grips: "",
  },
  {
    s_no: "420",
    parent: "Valves",
    name: "PCV Down Stream",
    legend: "PRV",
    suffix: "A/B",
    object: "PCVDownStream",
    svg: "",
    png: "",
    grips: "",
  },
  {
    s_no: "421",
    parent: "Valves",
    name: "PCV Up Stream",
    legend: "PRV",
    suffix: "A/B",
    object: "PCVUpStream",
    svg: "",
    png: "",
    grips: "",
  },
  {
    s_no: "422",
    parent: "Valves",
    name: "Hand Operated Valve",
    legend: "PRV",
    suffix: "A/B",
    object: "HandOperatedValve",
    svg: "",
    png: "",
    grips: "",
  },
  {
    s_no: "423",
    parent: "Valves",
    name: "Plunger Operated Valve",
    legend: "PRV",
    suffix: "A/B",
    object: "PlungerOperatedValve",
    svg: "",
    png: "",
    grips: "",
  },
  {
    s_no: "424",
    parent: "Valves",
    name: "Pilot Operated Valve",
    legend: "PRV",
    suffix: "A/B",
    object: "PilotOperatedValve",
    svg: "",
    png: "",
    grips: "",
  },
  {
    s_no: "425",
    parent: "Valves",
    name: "4 way Valve",
    legend: "PRV",
    suffix: "A/B",
    object: "4WayValve",
    svg: "",
    png: "",
    grips: "",
  },
  {
    s_no: "426",
    parent: "Valves",
    name: "Needle Valve",
    legend: "PRV",
    suffix: "A/B",
    object: "NeedleValve",
    svg: "",
    png: "",
    grips: "",
  },
  {
    s_no: "427",
    parent: "Valves",
    name: "Positive Choke",
    legend: "PRV",
    suffix: "A/B",
    object: "PositiveChoke",
    svg: "",
    png: "",
    grips: "",
  },
  {
    s_no: "428",
    parent: "Valves",
    name: "Adjustable Choke",
    legend: "PRV",
    suffix: "A/B",
    object: "AdjustableChoke",
    svg: "",
    png: "",
    grips: "",
  },
  {
    s_no: "429",
    parent: "Valves",
    name: "Motor Operated Valve",
    legend: "PRV",
    suffix: "A/B",
    object: "MotorOperatedValve",
    svg: "",
    png: "",
    grips: "",
  },
  {
    s_no: "501",
    parent: "Fittings",
    name: "Expansion Joint",
    legend: "FT",
    suffix: "",
    object: "ExpansionJoint",
    svg: "",
    png: "",
    grips: "",
  },
  {
    s_no: "502",
    parent: "Fittings",
    name: "Hose Connector ",
    legend: "FT",
    suffix: "",
    object: "HoseConnector",
    svg: "",
    png: "",
    grips: "",
  },
  {
    s_no: "503",
    parent: "Fittings",
    name: "Flexible Hose",
    legend: "FT",
    suffix: "",
    object: "FlexibleHose",
    svg: "",
    png: "",
    grips: "",
  },
  {
    s_no: "504",
    parent: "Fittings",
    name: "Spectacle Blind",
    legend: "FT",
    suffix: "",
    object: "SpectacleBlind",
    svg: "",
    png: "",
    grips: "",
  },
  {
    s_no: "505",
    parent: "Fittings",
    name: "Line Blind",
    legend: "FT",
    suffix: "",
    object: "LineBlind",
    svg: "",
    png: "",
    grips: "",
  },
  {
    s_no: "506",
    parent: "Fittings",
    name: "Reducer/Expander",
    legend: "FT",
    suffix: "",
    object: "ReducerExpander",
    svg: "",
    png: "",
    grips: "",
  },
  {
    s_no: "507",
    parent: "Fittings",
    name: "Blind Flange",
    legend: "FT",
    suffix: "",
    object: "BlindFlange",
    svg: "",
    png: "",
    grips: "",
  },
  {
    s_no: "508",
    parent: "Fittings",
    name: "Drain Funnel",
    legend: "FT",
    suffix: "",
    object: "DraingFunnel",
    svg: "",
    png: "",
    grips: "",
  },
  {
    s_no: "509",
    parent: "Fittings",
    name: "Threaded Cap",
    legend: "FT",
    suffix: "",
    object: "Threaded Cap",
    svg: "",
    png: "",
    grips: "",
  },
  {
    s_no: "510",
    parent: "Fittings",
    name: "Orifice",
    legend: "FT",
    suffix: "",
    object: "Orifice",
    svg: "",
    png: "",
    grips: "",
  },
  {
    s_no: "511",
    parent: "Fittings",
    name: "Venturi Meter",
    legend: "FT",
    suffix: "",
    object: "VenturiMeter",
    svg: "",
    png: "",
    grips: "",
  },
  {
    s_no: "512",
    parent: "Fittings",
    name: "Steam Trap",
    legend: "FT",
    suffix: "",
    object: "SteamTrap",
    svg: "",
    png: "",
    grips: "",
  },
  {
    s_no: "513",
    parent: "Fittings",
    name: "Vent with Goose Neck",
    legend: "FT",
    suffix: "",
    object: "VentGooseNeck",
    svg: "",
    png: "",
    grips: "",
  },
  {
    s_no: "514",
    parent: "Fittings",
    name: "Sight Glass",
    legend: "FT",
    suffix: "",
    object: "SlightGlass",
    svg: "",
    png: "",
    grips: "",
  },
  {
    s_no: "515",
    parent: "Fittings",
    name: "Union",
    legend: "FT",
    suffix: "",
    object: "Union",
    svg: "",
    png: "",
    grips: "",
  },
  {
    s_no: "516",
    parent: "Fittings",
    name: "Coupling",
    legend: "FT",
    suffix: "",
    object: "Coupling",
    svg: "",
    png: "",
    grips: "",
  },
  {
    s_no: "517",
    parent: "Fittings",
    name: "Adaptor",
    legend: "FT",
    suffix: "",
    object: "Adaptor",
    svg: "",
    png: "",
    grips: "",
  },
  {
    s_no: "518",
    parent: "Fittings",
    name: "Flow Element",
    legend: "FT",
    suffix: "",
    object: "FlowElement",
    svg: "",
    png: "",
    grips: "",
  },
  {
    s_no: "519",
    parent: "Fittings",
    name: "Turbine Meter",
    legend: "FT",
    suffix: "",
    object: "TurbineMeter",
    svg: "",
    png: "",
    grips: "",
  },
  {
    s_no: "520",
    parent: "Fittings",
    name: "Position Displacement Meter",
    legend: "FT",
    suffix: "",
    object: "PositiveDisplacementMeter",
    svg: "",
    png: "",
    grips: "",
  },
  {
    s_no: "521",
    parent: "Fittings",
    name: "Rotameter",
    legend: "FT",
    suffix: "",
    object: "Rotameter",
    svg: "",
    png: "",
    grips: "",
  },
  {
    s_no: "522",
    parent: "Fittings",
    name: "Sonic Meter",
    legend: "FT",
    suffix: "",
    object: "SonicMeter",
    svg: "",
    png: "",
    grips: "",
  },
  {
    s_no: "523",
    parent: "Fittings",
    name: "Magnetic Meter",
    legend: "FT",
    suffix: "",
    object: "MagneticMeter",
    svg: "",
    png: "",
    grips: "",
  },
  {
    s_no: "524",
    parent: "Fittings",
    name: "Pitot Tube",
    legend: "FT",
    suffix: "",
    object: "PilotTube",
    svg: "",
    png: "",
    grips: "",
  },
  {
    s_no: "525",
    parent: "Fittings",
    name: "Drain Plugged",
    legend: "FT",
    suffix: "",
    object: "DrainPlugged",
    svg: "",
    png: "",
    grips: "",
  },
  {
    s_no: "526",
    parent: "Fittings",
    name: "Drain Flanged",
    legend: "FT",
    suffix: "",
    object: "DrainFlanged",
    svg: "",
    png: "",
    grips: "",
  },
  {
    s_no: "527",
    parent: "Fittings",
    name: "Straightening Vanes",
    legend: "FT",
    suffix: "",
    object: "StraighteningVanes",
    svg: "",
    png: "",
    grips: "",
  },
  {
    s_no: "528",
    parent: "Fittings",
    name: "Analyser",
    legend: "FT",
    suffix: "",
    object: "Analyser",
    svg: "",
    png: "",
    grips: "",
  },
  {
    s_no: "529",
    parent: "Fittings",
    name: "Filter",
    legend: "FT",
    suffix: "",
    object: "Filter",
    svg: "",
    png: "",
    grips: "",
  },
  {
    s_no: "530",
    parent: "Fittings",
    name: "Filter",
    legend: "FT",
    suffix: "",
    object: "Filter",
    svg: "",
    png: "",
    grips: "",
  },
  {
    s_no: "531",
    parent: "Fittings",
    name: "T type Strainer",
    legend: "FT",
    suffix: "",
    object: "TTypeStrainer",
    svg: "",
    png: "",
    grips: "",
  },
  {
    s_no: "532",
    parent: "Fittings",
    name: "Y type Strainer",
    legend: "FT",
    suffix: "",
    object: "YTypeStrainer",
    svg: "",
    png: "",
    grips: "",
  },
  {
    s_no: "533",
    parent: "Fittings",
    name: "Temporary Strainer",
    legend: "FT",
    suffix: "",
    object: "TemporaryStrainer",
    svg: "",
    png: "",
    grips: "",
  },
  {
    s_no: "534",
    parent: "Fittings",
    name: "Basket Strainer",
    legend: "FT",
    suffix: "",
    object: "BasketStrainer",
    svg: "",
    png: "",
    grips: "",
  },
  {
    s_no: "535",
    parent: "Fittings",
    name: "Flame Arrester",
    legend: "FT",
    suffix: "",
    object: "FlameArrester",
    svg: "",
    png: "",
    grips: "",
  },
  {
    s_no: "536",
    parent: "Fittings",
    name: "Cone type Strainer",
    legend: "FT",
    suffix: "",
    object: "ConeTypeStrainer",
    svg: "",
    png: "",
    grips: "",
  },
  {
    s_no: "537",
    parent: "Fittings",
    name: "Sample Point",
    legend: "FT",
    suffix: "",
    object: "SamplePoint",
    svg: "",
    png: "",
    grips: "",
  },
  {
    s_no: "538",
    parent: "Fittings",
    name: "Pipe Cap Welded",
    legend: "FT",
    suffix: "",
    object: "PipeCapWelded",
    svg: "",
    png: "",
    grips: "",
  },
  {
    s_no: "601",
    parent: "Instrumentation Symbol",
    name: "Instrument Air Signal",
    legend: "",
    suffix: "",
    object: "InstrumentAirSignal",
    svg: "",
    png: "",
    grips: "",
  },
  {
    s_no: "602",
    parent: "Instrumentation Symbol",
    name: "Instrument Electric Signal",
    legend: "",
    suffix: "",
    object: "InstrumentElectricSignal",
    svg: "",
    png: "",
    grips: "",
  },
  {
    s_no: "603",
    parent: "Instrumentation Symbol",
    name: "Instrument Supply Lines",
    legend: "",
    suffix: "",
    object: "InstrumentSupplyLines",
    svg: "",
    png: "",
    grips: "",
  },
  {
    s_no: "604",
    parent: "Instrumentation Symbol",
    name: "Instrument Cappillary Tubing",
    legend: "",
    suffix: "",
    object: "InstrumentCappillarTubing",
    svg: "",
    png: "",
    grips: "",
  },
  {
    s_no: "605",
    parent: "Instrumentation Symbol",
    name: "Hydraulic Lines",
    legend: "",
    suffix: "",
    object: "HydraulicLines",
    svg: "",
    png: "",
    grips: "",
  },
  {
    s_no: "606",
    parent: "Instrumentation Symbol",
    name: "Software Connections",
    legend: "",
    suffix: "",
    object: "SoftwareConnections",
    svg: "",
    png: "",
    grips: "",
  },
  {
    s_no: "607",
    parent: "Instrumentation Symbol",
    name: "Locally Mounted Instruments",
    legend: "",
    suffix: "",
    object: "LocallyMountedInstruments",
    svg: "",
    png: "",
    grips: "",
  },
  {
    s_no: "608",
    parent: "Instrumentation Symbol",
    name: "Instrument Mounted on Main Panel",
    legend: "",
    suffix: "",
    object: "InstrumentMountedMainPanel",
    svg: "",
    png: "",
    grips: "",
  },
  {
    s_no: "609",
    parent: "Instrumentation Symbol",
    name: "Instrument Mounted on Local Panel",
    legend: "",
    suffix: "",
    object: "InstrumentMountedLocalPanel",
    svg: "",
    png: "",
    grips: "",
  },
  {
    s_no: "610",
    parent: "Instrumentation Symbol",
    name: "Transmitter Locally Mounted",
    legend: "",
    suffix: "",
    object: "TransmitterLocallyMounted",
    svg: "",
    png: "",
    grips: "",
  },
  {
    s_no: "611",
    parent: "Instrumentation Symbol",
    name: "Transmitter Panel Mounted",
    legend: "",
    suffix: "",
    object: "TransmitterPanelMounted",
    svg: "",
    png: "",
    grips: "",
  },
  {
    s_no: "612",
    parent: "Instrumentation Symbol",
    name: "Computer",
    legend: "",
    suffix: "",
    object: "Computer",
    svg: "",
    png: "",
    grips: "",
  },
  {
    s_no: "613",
    parent: "Instrumentation Symbol",
    name: "Computer Local Panel",
    legend: "",
    suffix: "",
    object: "CompuerLocalPanel",
    svg: "",
    png: "",
    grips: "",
  },
  {
    s_no: "614",
    parent: "Instrumentation Symbol",
    name: "DCS/DIDC",
    legend: "",
    suffix: "",
    object: "DCS",
    svg: "",
    png: "",
    grips: "",
  },
  {
    s_no: "615",
    parent: "Instrumentation Symbol",
    name: "Gas Filter",
    legend: "",
    suffix: "",
    object: "GasFilter",
    svg: "",
    png: "",
    grips: "",
  },
  {
    s_no: "616",
    parent: "Instrumentation Symbol",
    name: "Interlock",
    legend: "",
    suffix: "",
    object: "Interlock",
    svg: "",
    png: "",
    grips: "",
  },
  {
    s_no: "617",
    parent: "Instrumentation Symbol",
    name: "Rear Panel Intrument",
    legend: "",
    suffix: "",
    object: "RearPanelIntrument",
    svg: "",
    png: "",
    grips: "",
  },
  {
    s_no: "618",
    parent: "Instrumentation Symbol",
    name: "Running Light(local)",
    legend: "",
    suffix: "",
    object: "RunningLightLocal",
    svg: "",
    png: "",
    grips: "",
  },
  {
    s_no: "619",
    parent: "Instrumentation Symbol",
    name: "Running Ligth(Panel)",
    legend: "",
    suffix: "",
    object: "RunningLightPanel",
    svg: "",
    png: "",
    grips: "",
  },
  {
    s_no: "620",
    parent: "Instrumentation Symbol",
    name: "Running Light(local panel)",
    legend: "",
    suffix: "",
    object: "RunningLightLocalPanel",
    svg: "",
    png: "",
    grips: "",
  },
  {
    s_no: "621",
    parent: "Instrumentation Symbol",
    name: "Remote Telemetric Unit",
    legend: "",
    suffix: "",
    object: "RemoteTelemetricUnit",
    svg: "",
    png: "",
    grips: "",
  },
  {
    s_no: "622",
    parent: "Instrumentation Symbol",
    name: "Inlet Size",
    legend: "",
    suffix: "",
    object: "InletSize",
    svg: "",
    png: "",
    grips: "",
  },
  {
    s_no: "623",
    parent: "Instrumentation Symbol",
    name: "Rupture Disk",
    legend: "",
    suffix: "",
    object: "RuptureDisk",
    svg: "",
    png: "",
    grips: "",
  },
  {
    s_no: "624",
    parent: "Instrumentation Symbol",
    name: "Rotameter",
    legend: "",
    suffix: "",
    object: "Rotameter",
    svg: "",
    png: "",
    grips: "",
  },
  {
    s_no: "625",
    parent: "Instrumentation Symbol",
    name: "Diaphragm Seal",
    legend: "",
    suffix: "",
    object: "DiaphragmSeal",
    svg: "",
    png: "",
    grips: "",
  },
  {
    s_no: "626",
    parent: "Instrumentation Symbol",
    name: "Breather Valve",
    legend: "",
    suffix: "",
    object: "BreatherValve",
    svg: "",
    png: "",
    grips: "",
  },
  {
    s_no: "627",
    parent: "Instrumentation Symbol",
    name: "Programmable Logic Control",
    legend: "PLC",
    suffix: "",
    object: "ProgrammableLogicControl",
    svg: "",
    png: "",
    grips: "",
  },
  {
    s_no: "628",
    parent: "Instrumentation Symbol",
    name: "Programmable Logic Control on Local Panel",
    legend: "PLC",
    suffix: "",
    object: "ProgrammableLogicControlLocalPanel",
    svg: "",
    png: "",
    grips: "",
  },
  {
    s_no: "701",
    parent: "Pumps",
    name: "Centrifugal Pumps",
    legend: "P",
    suffix: "A/B",
    object: "CentrifugalPump",
    svg: "",
    png: "",
    grips: "",
  },
  {
    s_no: "702",
    parent: "Pumps",
    name: "Positive Displacement Pump",
    legend: "P",
    suffix: "A/B",
    object: "PositiveDisplacementPump",
    svg: "",
    png: "",
    grips: "",
  },
  {
    s_no: "703",
    parent: "Pumps ",
    name: "Duplex Pump ",
    legend: "P",
    suffix: "A/B",
    object: "DuplexPump",
    svg: "",
    png: "",
    grips: "",
  },
  {
    s_no: "704",
    parent: "Pumps",
    name: "Proportioning Pump",
    legend: "P",
    suffix: "A/B",
    object: "ProportioningPump",
    svg: "",
    png: "",
    grips: "",
  },
  {
    s_no: "705",
    parent: "Pumps",
    name: "Hand Pump with Drum",
    legend: "P",
    suffix: "A/B",
    object: "HandPumpWithDrum",
    svg: "",
    png: "",
    grips: "",
  },
  {
    s_no: "706",
    parent: "Pumps",
    name: "Ejector (vapour service)",
    legend: "P",
    suffix: "A/B",
    object: "EjectorVaporService",
    svg: "",
    png: "",
    grips: "",
  },
  {
    s_no: "707",
    parent: "Pumps",
    name: "Blowing Egg",
    legend: "P",
    suffix: "A/B",
    object: "BlowingEgg",
    svg: "",
    png: "",
    grips: "",
  },
  {
    s_no: "708",
    parent: "Pumps",
    name: "Reciprocating Pump",
    legend: "P",
    suffix: "A/B",
    object: "ReciprocatingPump",
    svg: "",
    png: "",
    grips: "",
  },
  {
    s_no: "709",
    parent: "Pumps",
    name: "Plunger Pump",
    legend: "P",
    suffix: "A/B",
    object: "PlungerPump",
    svg: "",
    png: "",
    grips: "",
  },
  {
    s_no: "801",
    parent: "Compressors",
    name: "Centrifugal Compressor",
    legend: "C",
    suffix: "A/B",
    object: "CentrifugalCompressor",
    svg: "",
    png: "",
    grips: "",
  },
  {
    s_no: "802",
    parent: "Compressors",
    name: "Positive Displacement Compressor",
    legend: "C",
    suffix: "A/B",
    object: "PositiveDisplacementCompressor",
    svg: "",
    png: "",
    grips: "",
  },
  {
    s_no: "803",
    parent: "Compressors",
    name: "Reciprocating Compressor",
    legend: "C",
    suffix: "A/B",
    object: "ReciprocatingCompressor",
    svg: "",
    png: "",
    grips: "",
  },
  {
    s_no: "804",
    parent: "Compressors",
    name: "Ejector Compressor",
    legend: "C",
    suffix: "A/B",
    object: "EjectorCompressor",
    svg: "",
    png: "",
    grips: "",
  },
  {
    s_no: "805",
    parent: "Compressors",
    name: "Fan",
    legend: "C",
    suffix: "A/B",
    object: "Fan",
    svg: "",
    png: "",
    grips: "",
  },
  {
    s_no: "806",
    parent: "Compressors",
    name: "Turbine  ",
    legend: "C",
    suffix: "A/B",
    object: "Turbine",
    svg: "",
    png: "",
    grips: "",
  },
  {
    s_no: "901",
    parent: "Heating or Cooling Arrangements",
    name: "Immersion Coil",
    legend: "E",
    suffix: "",
    object: "ImmersionCoil",
    svg: "",
    png: "",
    grips: "",
  },
  {
    s_no: "902",
    parent: "Heating or Cooling Arrangements",
    name: "Exchanger (in pfd)",
    legend: "E",
    suffix: "",
    object: "Exchanger",
    svg: "",
    png: "",
    grips: "",
  },
  {
    s_no: "903",
    parent: "Heating or Cooling Arrangements",
    name: "Heat Exchanger",
    legend: "E",
    suffix: "",
    object: "HeatExchanger",
    svg: "",
    png: "",
    grips: "",
  },
  {
    s_no: "904",
    parent: "Heating or Cooling Arrangements",
    name: "Exchanger  ",
    legend: "E",
    suffix: "",
    object: "Exchanger",
    svg: "",
    png: "",
    grips: "",
  },
  {
    s_no: "905",
    parent: "Heating or Cooling Arrangements",
    name: "Exchanger",
    legend: "E",
    suffix: "",
    object: "Exchanger905",
    svg: "",
    png: "",
    grips: "",
  },
  {
    s_no: "906",
    parent: "Heating or Cooling Arrangements",
    name: "Kettle Reboiler",
    legend: "E",
    suffix: "",
    object: "KettleReboiler",
    svg: "",
    png: "",
    grips: "",
  },
  {
    s_no: "907",
    parent: "Heating or Cooling Arrangements",
    name: "Kettle Reboiler",
    legend: "E",
    suffix: "",
    object: "KettleReboiler907",
    svg: "",
    png: "",
    grips: "",
  },
  {
    s_no: "908",
    parent: "Heating or Cooling Arrangements",
    name: "Kettle Reboiler 2 - Bundle",
    legend: "E",
    suffix: "",
    object: "KettleReboilerBundle",
    svg: "",
    png: "",
    grips: "",
  },
  {
    s_no: "909",
    parent: "Heating or Cooling Arrangements",
    name: "Tabular Coil",
    legend: "E",
    suffix: "",
    object: "TabularCoil",
    svg: "",
    png: "",
    grips: "",
  },
  {
    s_no: "910",
    parent: "Heating or Cooling Arrangements",
    name: "Jacket ",
    legend: "E",
    suffix: "",
    object: "Jacket",
    svg: "",
    png: "",
    grips: "",
  },
  {
    s_no: "911",
    parent: "Heating or Cooling Arrangements",
    name: "Natural Draught Cooling Tower",
    legend: "E",
    suffix: "",
    object: "NaturalDraughtCoolingTower",
    svg: "",
    png: "",
    grips: "",
  },
  {
    s_no: "912",
    parent: "Heating or Cooling Arrangements",
    name: "Induced Draught Cooling Tower",
    legend: "E",
    suffix: "",
    object: "InducedDraughtCoolingTower",
    svg: "",
    png: "",
    grips: "",
  },
  {
    s_no: "913",
    parent: "Heating or Cooling Arrangements",
    name: "Air Blown Cooler",
    legend: "E",
    suffix: "",
    object: "AirBlownCooler",
    svg: "",
    png: "",
    grips: "",
  },
  {
    s_no: "914",
    parent: "Heating or Cooling Arrangements",
    name: "Trickle Cooler",
    legend: "E",
    suffix: "",
    object: "TrickleCooler",
    svg: "",
    png: "",
    grips: "",
  },
  {
    s_no: "915",
    parent: "Heating or Cooling Arrangements",
    name: "Plate Type Heat Exchanger",
    legend: "E",
    suffix: "",
    object: "PlateTypeHeatExchanger",
    svg: "",
    png: "",
    grips: "",
  },
  {
    s_no: "916",
    parent: "Heating or Cooling Arrangements",
    name: "Air Cooler with Fan and Motor",
    legend: "E",
    suffix: "",
    object: "AirCoolerFanMotor",
    svg: "",
    png: "",
    grips: "",
  },
  {
    s_no: "917",
    parent: "Heating or Cooling Arrangements",
    name: "Contact Condenser",
    legend: "E",
    suffix: "",
    object: "ContactCondenser",
    svg: "",
    png: "",
    grips: "",
  },
  {
    s_no: "918",
    parent: "Heating or Cooling Arrangements",
    name: "Desuper Heater",
    legend: "E",
    suffix: "",
    object: "DesuperHeater",
    svg: "",
    png: "",
    grips: "",
  },
  {
    s_no: "919",
    parent: "Furnance and Boilers",
    name: "One Cell Fired Heater/Furnance",
    legend: "E",
    suffix: "",
    object: "OneCellFiredHeaterFurnace",
    svg: "",
    png: "",
    grips: "",
  },
  {
    s_no: "920",
    parent: "Furnance and Boilers",
    name: "Two Cell Fired Heater/Furnance",
    legend: "E",
    suffix: "",
    object: "TwoCellFiredHeaterFurnace",
    svg: "",
    png: "",
    grips: "",
  },
  {
    s_no: "1001",
    parent: "Furnance and Boilers",
    name: "Solid Fuel Furnance",
    legend: "E",
    suffix: "",
    object: "SolidFuelFurnace",
    svg: "",
    png: "",
    grips: "",
  },
  {
    s_no: "1002",
    parent: "Furnance and Boilers",
    name: "Oil, Gas or Pulverized Fuel Furnance",
    legend: "E",
    suffix: "",
    object: "OilGasOrPulverizedFuelFurnace",
    svg: "",
    png: "",
    grips: "",
  },
  {
    s_no: "1003",
    parent: "Furnance and Boilers",
    name: "Electric Furnance",
    legend: "E",
    suffix: "",
    object: "ElectricFurnance",
    svg: "",
    png: "",
    grips: "",
  },
  {
    s_no: "1004",
    parent: "Furnance and Boilers",
    name: "Fired Boiler",
    legend: "E",
    suffix: "",
    object: "FiredBoiler",
    svg: "",
    png: "",
    grips: "",
  },
  {
    s_no: "1005",
    parent: "Furnance and Boilers",
    name: "Waste Heat Boiler",
    legend: "E",
    suffix: "",
    object: "WasteHeatBoiler",
    svg: "",
    png: "",
    grips: "",
  },
  {
    s_no: "1101",
    parent: "Process Vessels",
    name: "Horizontal Vessel",
    legend: "V",
    suffix: "",
    object: "HorizontalVessel",
    svg: "",
    png: "",
    grips: "",
  },
  {
    s_no: "1102",
    parent: "Process Vessels",
    name: "Vertical Vessel",
    legend: "V",
    suffix: "",
    object: "VerticalVessel",
    svg: "",
    png: "",
    grips: "",
  },
  {
    s_no: "1103",
    parent: "Process Vessels",
    name: "Jacketed Vessel",
    legend: "V",
    suffix: "",
    object: "JacketedVessel",
    svg: "",
    png: "",
    grips: "",
  },
  {
    s_no: "1104",
    parent: "Process Vessels",
    name: "Packed Vessel",
    legend: "V",
    suffix: "",
    object: "PackedVessel",
    svg: "",
    png: "",
    grips: "",
  },
  {
    s_no: "1105",
    parent: "Process Vessels",
    name: "Evaporator",
    legend: "V",
    suffix: "",
    object: "Evaporator",
    svg: "",
    png: "",
    grips: "",
  },
  {
    s_no: "1106",
    parent: "Process Vessels",
    name: "Crystallizer",
    legend: "V",
    suffix: "",
    object: "Crystallizer",
    svg: "",
    png: "",
    grips: "",
  },
  {
    s_no: "1107",
    parent: "Process Vessels",
    name: "Autoclave",
    legend: "V",
    suffix: "",
    object: "Autoclave",
    svg: "",
    png: "",
    grips: "",
  },
  {
    s_no: "1108",
    parent: "Process Vessels",
    name: "Construction Inside Containers, Columns, Towers and Reactors",
    legend: "V",
    suffix: "",
    object: "ConstructionInsideContainers, Columns, Towersand Reactors",
    svg: "",
    png: "",
    grips: "",
  },
  {
    s_no: "1108A",
    parent: "Process Vessels",
    name: "Plates/Trays (For mass Transfer)",
    legend: "V",
    suffix: "",
    object: "TraysOrPlates",
    svg: "",
    png: "",
    grips: "",
  },
  {
    s_no: "1108B",
    parent: "Process Vessels",
    name: "Fluidized Bed",
    legend: "V",
    suffix: "",
    object: "FluidizedBed",
    svg: "",
    png: "",
    grips: "",
  },
  {
    s_no: "1109",
    parent: "Process Vessels",
    name: "Multi Bed Packed Column",
    legend: "V",
    suffix: "",
    object: "MultiBedPackedColumn",
    svg: "",
    png: "",
    grips: "",
  },
  {
    s_no: "1110",
    parent: "Process Vessels",
    name: "Vessel with Boot",
    legend: "V",
    suffix: "",
    object: "VesselBoot",
    svg: "",
    png: "",
    grips: "",
  },
  {
    s_no: "1111",
    parent: "Process Vessels",
    name: "Deaerator",
    legend: "V",
    suffix: "",
    object: "Deaerator",
    svg: "",
    png: "",
    grips: "",
  },
  {
    s_no: "1112",
    parent: "Process Vessels",
    name: "Flanged Vessel",
    legend: "V",
    suffix: "",
    object: "FlangedVessel",
    svg: "",
    png: "",
    grips: "",
  },
  {
    s_no: "1113",
    parent: "Process Vessels",
    name: "Double Flanged Vessel",
    legend: "V",
    suffix: "",
    object: "DoubleFlangedVessel",
    svg: "",
    png: "",
    grips: "",
  },
  {
    s_no: "1114",
    parent: "Process Vessels",
    name: "Conical Bottom Vessel",
    legend: "V",
    suffix: "",
    object: "ConicalBottomVessel",
    svg: "",
    png: "",
    grips: "",
  },
  {
    s_no: "1115",
    parent: "Process Vessels",
    name: "Vessel with One - Sump",
    legend: "V",
    suffix: "",
    object: "VesselOneSump",
    svg: "",
    png: "",
    grips: "",
  },
  {
    s_no: "1116",
    parent: "Process Vessels",
    name: "Vessel with Two - Sumps",
    legend: "V",
    suffix: "",
    object: "VesselTwoSumps",
    svg: "",
    png: "",
    grips: "",
  },
  {
    s_no: "1201",
    parent: "Storage Vessels/ Tanks",
    name: "Fixed Roof Tank",
    legend: "TK",
    suffix: "",
    object: "FixedRoofTank",
    svg: "",
    png: "",
    grips: "",
  },
  {
    s_no: "1202",
    parent: "Storage Vessels/ Tanks",
    name: "Floating Roof Tank",
    legend: "TK",
    suffix: "",
    object: "FloatingRoofTank",
    svg: "",
    png: "",
    grips: "",
  },
  {
    s_no: "1203",
    parent: "Storage Vessels/ Tanks",
    name: "Floating Cum Fixed Root Tank",
    legend: "TK",
    suffix: "",
    object: "FloatingCumFixedRootTank",
    svg: "",
    png: "",
    grips: "",
  },
  {
    s_no: "1204",
    parent: "Storage Vessels/ Tanks",
    name: "Gas Holder, Wet Seal",
    legend: "TK",
    suffix: "",
    object: "GasHolderWetSeal",
    svg: "",
    png: "",
    grips: "",
  },
  {
    s_no: "1205",
    parent: "Storage Vessels/ Tanks",
    name: "Gas Holder, Dry Seal",
    legend: "TK",
    suffix: "",
    object: "GasHolderDrySeal",
    svg: "",
    png: "",
    grips: "",
  },
  {
    s_no: "1206",
    parent: "Storage Vessels/ Tanks",
    name: "Pressure Storage Horton Sphere",
    legend: "TK",
    suffix: "",
    object: "PressureStorageHortonSphere",
    svg: "",
    png: "",
    grips: "",
  },
  {
    s_no: "1301",
    parent: "Dryers",
    name: "Batch Tray Drier",
    legend: "D",
    suffix: "",
    object: "BatchTrayDrier",
    svg: "",
    png: "",
    grips: "",
  },
  {
    s_no: "1302",
    parent: "Dryers",
    name: "Spray Drier",
    legend: "D",
    suffix: "",
    object: "SprayDrier",
    svg: "",
    png: "",
    grips: "",
  },
  {
    s_no: "1303",
    parent: "Dryers",
    name: "Continuous Drier",
    legend: "D",
    suffix: "",
    object: "ContinuousDryer",
    svg: "",
    png: "",
    grips: "",
  },
  {
    s_no: "1304",
    parent: "Dryers",
    name: "Rotary Drier or Kiln",
    legend: "D",
    suffix: "",
    object: "RotaryDrier",
    svg: "",
    png: "",
    grips: "",
  },
  {
    s_no: "1401",
    parent: "Size Reduction Equipments",
    name: "Size Reducing Equipment",
    legend: "SR",
    suffix: "",
    object: "SizeReducingEquipment",
    svg: "",
    png: "",
    grips: "",
  },
  {
    s_no: "1402",
    parent: "Size Reduction Equipments",
    name: "Breaker, Gyratory",
    legend: "SR",
    suffix: "",
    object: "BreakerGyratory",
    svg: "",
    png: "",
    grips: "",
  },
  {
    s_no: "1403",
    parent: "Size Reduction Equipments",
    name: "Breaker Hammer Mill Impact Mill",
    legend: "SR",
    suffix: "",
    object: "BreakerHammerMillImpactMill",
    svg: "",
    png: "",
    grips: "",
  },
  {
    s_no: "1404",
    parent: "Size Reduction Equipments",
    name: "Jaw Crusher",
    legend: "SR",
    suffix: "",
    object: "JawCrusher",
    svg: "",
    png: "",
    grips: "",
  },
  {
    s_no: "1404A",
    parent: "Size Reduction Equipments",
    name: "Roller Crusher",
    legend: "SR",
    suffix: "",
    object: "RollerCrusher",
    svg: "",
    png: "",
    grips: "",
  },
  {
    s_no: "1405",
    parent: "Size Reduction Equipments",
    name: "Grinder",
    legend: "SR",
    suffix: "",
    object: "Grinder",
    svg: "",
    png: "",
    grips: "",
  },
  {
    s_no: "1406",
    parent: "Size Reduction Equipments",
    name: "Ball or Tube Mill",
    legend: "SR",
    suffix: "",
    object: "BallTubeMill",
    svg: "",
    png: "",
    grips: "",
  },
  {
    s_no: "1501",
    parent: "Separators",
    name: "Cyclone or Hydrocyclone",
    legend: "SEP",
    suffix: "",
    object: "Cyclone",
    svg: "",
    png: "",
    grips: "",
  },
  {
    s_no: "1502",
    parent: "Separators",
    name: "Electrostatic Seperator",
    legend: "SEP",
    suffix: "",
    object: "ElectrostaticSeperator",
    svg: "",
    png: "",
    grips: "",
  },
  {
    s_no: "1503",
    parent: "Separators",
    name: "Seperators for Liquids, Decantors",
    legend: "SEP",
    suffix: "",
    object: "SeparatorsForLiquidsDecanter",
    svg: "",
    png: "",
    grips: "",
  },
  {
    s_no: "1504",
    parent: "Separators",
    name: "Thickener",
    legend: "SEP",
    suffix: "",
    object: "Thickener",
    svg: "",
    png: "",
    grips: "",
  },
  {
    s_no: "1505",
    parent: "Separators",
    name: "Screen",
    legend: "SEP",
    suffix: "",
    object: "Screen",
    svg: "",
    png: "",
    grips: "",
  },
  {
    s_no: "1601",
    parent: "Filters",
    name: "Filter Press",
    legend: "F",
    suffix: "",
    object: "FilterPress",
    svg: "",
    png: "",
    grips: "",
  },
  {
    s_no: "1602",
    parent: "Filters",
    name: "Suction Filter",
    legend: "F",
    suffix: "",
    object: "SuctionFilter",
    svg: "",
    png: "",
    grips: "",
  },
  {
    s_no: "1603",
    parent: "Filters",
    name: "Pressure Filter",
    legend: "F",
    suffix: "",
    object: "PressureFilter",
    svg: "",
    png: "",
    grips: "",
  },
  {
    s_no: "1604",
    parent: "Filters",
    name: "Gravity Filter",
    legend: "F",
    suffix: "",
    object: "GravityFilter",
    svg: "",
    png: "",
    grips: "",
  },
  {
    s_no: "1605",
    parent: "Filters",
    name: "Open Rotary",
    legend: "F",
    suffix: "",
    object: "OpenRotary",
    svg: "",
    png: "",
    grips: "",
  },
  {
    s_no: "1606",
    parent: "Filters",
    name: "Closed Rotary",
    legend: "F",
    suffix: "",
    object: "ClosedRotary",
    svg: "",
    png: "",
    grips: "",
  },
  {
    s_no: "1607",
    parent: "Filters",
    name: "Bag Filter",
    legend: "F",
    suffix: "",
    object: "BagFilter",
    svg: "",
    png: "",
    grips: "",
  },
  {
    s_no: "1701",
    parent: "Centrifuges",
    name: "Centrifuges",
    legend: "CF",
    suffix: "",
    object: "Centrifuges",
    svg: "",
    png: "",
    grips: "",
  },
  {
    s_no: "1702",
    parent: "Centrifuges",
    name: "Basket Centrifuges Batch or Continous",
    legend: "CF",
    suffix: "",
    object: "",
    svg: "",
    png: "",
    grips: "",
  },
  {
    s_no: "1703",
    parent: "Centrifuges",
    name: "Plate Centrifuge",
    legend: "CF",
    suffix: "",
    object: "",
    svg: "",
    png: "",
    grips: "",
  },
  {
    s_no: "1801",
    parent: "Stirrers",
    name: "General Symbol",
    legend: "M",
    suffix: "",
    object: "",
    svg: "",
    png: "",
    grips: "",
  },
  {
    s_no: "1802",
    parent: "Stirrers",
    name: "Sparger",
    legend: "M",
    suffix: "",
    object: "",
    svg: "",
    png: "",
    grips: "",
  },
  {
    s_no: "1901",
    parent: "Mixers",
    name: "Ribbon Blender",
    legend: "M",
    suffix: "",
    object: "",
    svg: "",
    png: "",
    grips: "",
  },
  {
    s_no: "1902",
    parent: "Mixers",
    name: "Kneader",
    legend: "M",
    suffix: "",
    object: "",
    svg: "",
    png: "",
    grips: "",
  },
  {
    s_no: "1903",
    parent: "Mixers",
    name: "Double Cone Blender",
    legend: "M",
    suffix: "",
    object: "",
    svg: "",
    png: "",
    grips: "",
  },
  {
    s_no: "1904",
    parent: "Mixers",
    name: "Ejector Mixer",
    legend: "M",
    suffix: "",
    object: "",
    svg: "",
    png: "",
    grips: "",
  },
  {
    s_no: "1905",
    parent: "Mixers",
    name: "Rotary Mixer",
    legend: "M",
    suffix: "",
    object: "",
    svg: "",
    png: "",
    grips: "",
  },
  {
    s_no: "1906",
    parent: "Mixers",
    name: "On - Line Mixer",
    legend: "M",
    suffix: "",
    object: "",
    svg: "",
    png: "",
    grips: "",
  },
  {
    s_no: "1907",
    parent: "Mixers",
    name: "Mixer",
    legend: "M",
    suffix: "",
    object: "",
    svg: "",
    png: "",
    grips: "",
  },
  {
    s_no: "1908",
    parent: "Mixers",
    name: "Sacony Mixer",
    legend: "M",
    suffix: "",
    object: "",
    svg: "",
    png: "",
    grips: "",
  },
  {
    s_no: "2001",
    parent: "Feeders",
    name: "General Symbol",
    legend: "FD",
    suffix: "",
    object: "GeneralSymbol",
    svg: "",
    png: "",
    grips: "",
  },
  {
    s_no: "2002",
    parent: "Feeders",
    name: "Vibrator Feeder",
    legend: "FD",
    suffix: "",
    object: "",
    svg: "",
    png: "",
    grips: "",
  },
  {
    s_no: "2003",
    parent: "Feeders",
    name: "Weigh Feeder",
    legend: "FD",
    suffix: "",
    object: "",
    svg: "",
    png: "",
    grips: "",
  },
  {
    s_no: "2004",
    parent: "Feeders",
    name: "Rotary Table Feeder, Revolving Plate Feeder",
    legend: "FD",
    suffix: "",
    object: "",
    svg: "",
    png: "",
    grips: "",
  },
  {
    s_no: "2005",
    parent: "Feeders",
    name: "Scraper Feeder",
    legend: "FD",
    suffix: "",
    object: "",
    svg: "",
    png: "",
    grips: "",
  },
  {
    s_no: "2006",
    parent: "Feeders",
    name: "Screw Feeder",
    legend: "FD",
    suffix: "",
    object: "",
    svg: "",
    png: "",
    grips: "",
  },
  {
    s_no: "2007",
    parent: "Feeders",
    name: "Rotary Feeder",
    legend: "FD",
    suffix: "",
    object: "",
    svg: "",
    png: "",
    grips: "",
  },
  {
    s_no: "2101",
    parent: "Conveyors",
    name: "Belt Conveyor",
    legend: "CV",
    suffix: "",
    object: "",
    svg: "",
    png: "",
    grips: "",
  },
  {
    s_no: "2102",
    parent: "Conveyors",
    name: "Scraper Conveyor",
    legend: "CV",
    suffix: "",
    object: "",
    svg: "",
    png: "",
    grips: "",
  },
  {
    s_no: "2103",
    parent: "Conveyors",
    name: "Vibrating Conveyor",
    legend: "CV",
    suffix: "",
    object: "",
    svg: "",
    png: "",
    grips: "",
  },
  {
    s_no: "2104",
    parent: "Conveyors",
    name: "Screw Conveyor",
    legend: "CV",
    suffix: "",
    object: "",
    svg: "",
    png: "",
    grips: "",
  },
  {
    s_no: "2105",
    parent: "Conveyors",
    name: "Bucket Conveyor",
    legend: "CV",
    suffix: "",
    object: "",
    svg: "",
    png: "",
    grips: "",
  },
  {
    s_no: "2106",
    parent: "Conveyors",
    name: "Roller Conveyor",
    legend: "CV",
    suffix: "",
    object: "",
    svg: "",
    png: "",
    grips: "",
  },
  {
    s_no: "2107",
    parent: "Conveyors",
    name: "Overhead Conveyor with Hooks",
    legend: "CV",
    suffix: "",
    object: "",
    svg: "",
    png: "",
    grips: "",
  },
  {
    s_no: "2107B",
    parent: "Conveyors",
    name: "Overhead Conveyor or Ropeway with Bucket or Carriers",
    legend: "CV",
    suffix: "",
    object: "",
    svg: "",
    png: "",
    grips: "",
  },
  {
    s_no: "2108A",
    parent: "Conveyors",
    name: "Fixed Hoist with Hook",
    legend: "CV",
    suffix: "",
    object: "",
    svg: "",
    png: "",
    grips: "",
  },
  {
    s_no: "2108B",
    parent: "Conveyors",
    name: "Travelling Hoist with Hook",
    legend: "CV",
    suffix: "",
    object: "",
    svg: "",
    png: "",
    grips: "",
  },
  {
    s_no: "2108C",
    parent: "Conveyors",
    name: "Travelling Hoist with Grab",
    legend: "CV",
    suffix: "",
    object: "",
    svg: "",
    png: "",
    grips: "",
  },
  {
    s_no: "2108D",
    parent: "Conveyors",
    name: "Air Floats",
    legend: "CV",
    suffix: "",
    object: "",
    svg: "",
    png: "",
    grips: "",
  },
  {
    s_no: "2201",
    parent: "Transport Vehicles",
    name: "Ship",
    legend: "TV",
    suffix: "",
    object: "",
    svg: "",
    png: "",
    grips: "",
  },
  {
    s_no: "2202",
    parent: "Transport Vehicles",
    name: "Wagon, Lorry, Truck",
    legend: "TV",
    suffix: "",
    object: "",
    svg: "",
    png: "",
    grips: "",
  },
  {
    s_no: "2203",
    parent: "Transport Vehicles",
    name: "Tanker",
    legend: "TV",
    suffix: "",
    object: "",
    svg: "",
    png: "",
    grips: "",
  },
  {
    s_no: "2204",
    parent: "Transport Vehicles",
    name: "Open Trailer",
    legend: "TV",
    suffix: "",
    object: "",
    svg: "",
    png: "",
    grips: "",
  },
  {
    s_no: "2205",
    parent: "Transport Vehicles",
    name: "Wagon with Bottom Hopper",
    legend: "TV",
    suffix: "",
    object: "",
    svg: "",
    png: "",
    grips: "",
  },
  {
    s_no: "2301",
    parent: "Miscellaneous",
    name: "Silencer",
    legend: "MISC",
    suffix: "",
    object: "",
    svg: "",
    png: "",
    grips: "",
  },
  {
    s_no: "2302",
    parent: "Miscellaneous",
    name: "Launcher Receiver",
    legend: "MISC",
    suffix: "",
    object: "",
    svg: "",
    png: "",
    grips: "",
  },
  {
    s_no: "2303",
    parent: "Miscellaneous",
    name: "Diesel Generator",
    legend: "MISC",
    suffix: "",
    object: "",
    svg: "",
    png: "",
    grips: "",
  },
  {
    s_no: "2304",
    parent: "Miscellaneous",
    name: "Turbine Generator",
    legend: "MISC",
    suffix: "",
    object: "",
    svg: "",
    png: "",
    grips: "",
  },
  {
    s_no: "2305",
    parent: "Miscellaneous",
    name: "Hose Reel",
    legend: "MISC",
    suffix: "",
    object: "",
    svg: "",
    png: "",
    grips: "",
  },
  {
    s_no: "2306A",
    parent: "Miscellaneous",
    name: "Well Head with One Bore(Single Completion)",
    legend: "MISC",
    suffix: "",
    object: "",
    svg: "",
    png: "",
    grips: "",
  },
  {
    s_no: "2306B",
    parent: "Miscellaneous",
    name: "Well Head with One Bore(Dual Completion)",
    legend: "MISC",
    suffix: "",
    object: "",
    svg: "",
    png: "",
    grips: "",
  },
  {
    s_no: "2307",
    parent: "Miscellaneous",
    name: "Sump Caisson",
    legend: "MISC",
    suffix: "",
    object: "",
    svg: "",
    png: "",
    grips: "",
  },
  {
    s_no: "2308A",
    parent: "Miscellaneous",
    name: "Flare",
    legend: "MISC",
    suffix: "",
    object: "",
    svg: "",
    png: "",
    grips: "",
  },
  {
    s_no: "2308B",
    parent: "Miscellaneous",
    name: "Flare Stack",
    legend: "MISC",
    suffix: "",
    object: "",
    svg: "",
    png: "",
    grips: "",
  },
  {
    s_no: "2309",
    parent: "Miscellaneous",
    name: "Chimney",
    legend: "MISC",
    suffix: "",
    object: "",
    svg: "",
    png: "",
    grips: "",
  },
  {
    s_no: "2310",
    parent: "Miscellaneous",
    name: "Scrapper Tee",
    legend: "MISC",
    suffix: "",
    object: "",
    svg: "",
    png: "",
    grips: "",
  },
  {
    s_no: "2311",
    parent: "Miscellaneous",
    name: "Atmospheric Vent",
    legend: "MISC",
    suffix: "",
    object: "",
    svg: "",
    png: "",
    grips: "",
  },
  {
    s_no: "2312",
    parent: "Miscellaneous",
    name: "Cylinder",
    legend: "MISC",
    suffix: "",
    object: "",
    svg: "",
    png: "",
    grips: "",
  },
  {
    s_no: "2313",
    parent: "Miscellaneous",
    name: "Graduated Cylinder",
    legend: "MISC",
    suffix: "",
    object: "",
    svg: "",
    png: "",
    grips: "",
  },
  {
    s_no: "2314",
    parent: "Miscellaneous",
    name: "Crane",
    legend: "MISC",
    suffix: "",
    object: "",
    svg: "",
    png: "",
    grips: "",
  },
  {
    s_no: "2315A",
    parent: "Miscellaneous",
    name: "Electrolytic Cell without Diaphragm",
    legend: "MISC",
    suffix: "",
    object: "",
    svg: "",
    png: "",
    grips: "",
  },
  {
    s_no: "2315B",
    parent: "Miscellaneous",
    name: "Electrolytic Cell with Diaphragm",
    legend: "MISC",
    suffix: "",
    object: "",
    svg: "",
    png: "",
    grips: "",
  },
  {
    s_no: "2316",
    parent: "Miscellaneous",
    name: "Turbine Drive",
    legend: "MISC",
    suffix: "",
    object: "",
    svg: "",
    png: "",
    grips: "",
  },
  {
    s_no: "2317",
    parent: "Miscellaneous",
    name: "Motor Drive",
    legend: "MISC",
    suffix: "",
    object: "",
    svg: "",
    png: "",
    grips: "",
  },
  {
    s_no: "2318",
    parent: "Miscellaneous",
    name: "Swivel Drain",
    legend: "MISC",
    suffix: "",
    object: "",
    svg: "",
    png: "",
    grips: "",
  },
  {
    s_no: "2319",
    parent: "Miscellaneous",
    name: "CBD - Symbol",
    legend: "MISC",
    suffix: "",
    object: "",
    svg: "",
    png: "",
    grips: "",
  },
  {
    s_no: "2320",
    parent: "Miscellaneous",
    name: "Sample Cooler",
    legend: "MISC",
    suffix: "",
    object: "",
    svg: "",
    png: "",
    grips: "",
  },
];
